import { GoogleGenAI } from "@google/genai";
import { BackgroundColor, ClothingOption } from "../types";

const processBackground = async (
  imageBase64: string,
  color: BackgroundColor,
  clothing: ClothingOption
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please set the API_KEY environment variable.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const model = "gemini-2.5-flash-image";

  // Clean base64 string
  const cleanBase64 = imageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");

  const colorName = color === BackgroundColor.WHITE ? "pure white" : "light blue";
  
  let clothingPrompt = "";
  if (clothing !== ClothingOption.NONE) {
      let outfitDesc = "";
      switch (clothing) {
          case ClothingOption.MALE_BLAZER:
              outfitDesc = "a professional black suit jacket with a white dress shirt and tie";
              break;
          case ClothingOption.FEMALE_BLAZER:
              outfitDesc = "a professional black formal blazer over a simple top";
              break;
          case ClothingOption.MALE_SHIRT:
              outfitDesc = "a crisp white formal button-down dress shirt";
              break;
          case ClothingOption.FEMALE_SHIRT:
              outfitDesc = "a professional white formal business shirt";
              break;
      }
      clothingPrompt = `3. CHANGE THE OUTFIT: Replace the person's current clothing with ${outfitDesc}. Ensure the fit is realistic, the neck connection is natural, and it looks like a high-quality professional headshot.`;
  } else {
      clothingPrompt = "3. KEEP THE PERSON'S CLOTHING EXACTLY AS IS. Do not alter their clothes.";
  }

  const prompt = `
    Task: Create a professional passport photo from this portrait.
    Instructions:
    1. Identify the person in the foreground.
    2. KEEP THE PERSON'S FACE AND HAIR EXACTLY AS IS. Do not alter facial features or identity.
    ${clothingPrompt}
    4. Replace the entire background with a solid ${colorName} color (Hex color code: ${color}).
    5. Ensure a clean, professional edge cutout.
    6. CRITICAL: DO NOT WRITE THE HEX CODE OR ANY TEXT ON THE IMAGE. The image must be text-free.
    7. Output only the modified image.
  `;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/png",
              data: cleanBase64,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    // Check for image in response parts
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      for (const part of candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export { processBackground };